server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: domain-header
          uri: lb://DOMAIN-HEADER
          predicates:
            - Path=/auth/**
        - id: security-jwt
          uri: lb://SECURITY-JWT
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: eureka-0